networks:
  dev:

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    networks:
      - dev
    expose:
      - 8000
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - dev

