networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"

    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html

    depends_on:
      - backend
      - frontend
    
    networks:
      - dev

  backend:
    build: ./backend
    networks:
      - dev
  
  frontend:
    build: 
      context: ./frontend
    networks:
      - dev
