"""Warnings

Revision ID: d0fcc9c66abb
Revises: 1964189d0653
Create Date: 2025-02-25 14:28:06.488282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0fcc9c66abb'
down_revision: Union[str, None] = '1964189d0653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('warnings', sa.Integer(), nullable=False, server_default='0'))    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'warnings')
    # ### end Alembic commands ###
